### ISSUE TITLE
plugin could not be loaded

### ISSUE THREAD

**Issue by bstecklum** [jefferyto/gedit-ex-mortis#3]
Gedit 3.218 on Ubuntu 18.04 fails to load the plugin
$ gedit 

(gedit:12249): libpeas-WARNING **: 12:10:07.979: Error importing plugin 'ex-mortis':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ex-mortis'

(gedit:12249): libpeas-WARNING **: 12:10:07.979: Error loading plugin 'ex-mortis'

**Comment by bstecklum** [comment]
Issue was because of incomplete installation. Plugin is activated now.
